### ISSUE TITLE
 DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by Philipp91** [scottburch/webpack-beep-plugin#1]
Getting this warning with the latest webpack version:

```
(node:24165) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at CompileBeepPlugin.apply (/mnt/c/Users/Philipp/repos/manniweb/node_modules/webpack-beep-plugin/webpack-beep-plugin.js:8:14)
    at webpack (/mnt/c/Users/Philipp/repos/manniweb/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/mnt/c/Users/Philipp/repos/manniweb/node_modules/webpack-cli/bin/cli.js:441:16)
    at yargs.parse (/mnt/c/Users/Philipp/repos/manniweb/node_modules/webpack-cli/bin/cli.js:528:3)
    at Object.parse (/mnt/c/Users/Philipp/repos/manniweb/node_modules/yargs/yargs.js:552:18)
    at /mnt/c/Users/Philipp/repos/manniweb/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/mnt/c/Users/Philipp/repos/manniweb/node_modules/webpack-cli/bin/cli.js:530:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/c/Users/Philipp/repos/manniweb/node_modules/webpack/bin/webpack.js:165:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

See also https://github.com/webpack/webpack/issues/6568

**Comment by Philipp91** [comment]
Do you have some spare time to release this fix?

**Comment by scottburch** [comment]
Did I not release it?  Sorry about that . Will do that today.

**Comment by scottburch** [comment]
Done

**Comment by Philipp91** [comment]
Thanks, it works!

**Comment by scottburch** [comment]
Don't thank me.  Your pull request. Thank you so much.
